# Generated by Django 2.2.4 on 2019-10-11 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo', '0002_auto_20191011_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='matricula',
            new_name='Carteira_de_Trabalho',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='pesssoa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='CPF',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Data_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
