# Generated by Django 2.2.4 on 2019-10-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_auto_20191011_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='data',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='numero',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='processo',
            new_name='Processo',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='texto',
            new_name='Texto',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='titulo',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='user',
            new_name='Usuario',
        ),
    ]
